" agda_unicode.vim - LaTeX-style bindings for Unicode input

" Superscripts
noremap! <buffer> ^0 ⁰
noremap! <buffer> ^1 ¹
noremap! <buffer> ^2 ²
noremap! <buffer> ^3 ³
noremap! <buffer> ^4 ⁴
noremap! <buffer> ^5 ⁵
noremap! <buffer> ^6 ⁶
noremap! <buffer> ^7 ⁷
noremap! <buffer> ^8 ⁸
noremap! <buffer> ^9 ⁹
noremap! <buffer> ^+ ⁺
noremap! <buffer> ^- ⁻
noremap! <buffer> ^= ⁼
noremap! <buffer> ^( ⁽
noremap! <buffer> ^) ⁾
noremap! <buffer> ^n ⁿ
noremap! <buffer> ^i ⁱ

" Subscripts
noremap! <buffer> \_0 ₀
noremap! <buffer> \_1 ₁
noremap! <buffer> \_2 ₂
noremap! <buffer> \_3 ₃
noremap! <buffer> \_4 ₄
noremap! <buffer> \_5 ₅
noremap! <buffer> \_6 ₆
noremap! <buffer> \_7 ₇
noremap! <buffer> \_8 ₈
noremap! <buffer> \_9 ₉
noremap! <buffer> \_+ ₊
noremap! <buffer> \_- ₋
noremap! <buffer> \_= ₌
noremap! <buffer> \_( ₍
noremap! <buffer> \_i ᵢ
noremap! <buffer> \_j ⱼ
noremap! <buffer> \_) ₎

" Arrows (but don't delay inserting comments)
noremap! <buffer> -> →
noremap! <buffer> -- --
noremap! <buffer> <-- ←
noremap! <buffer> <--> ↔
noremap! <buffer> ==> ⇒
noremap! <buffer> <== ⇐
noremap! <buffer> <==> ⇔

" Symbols from mathematics and logic, LaTeX style
noremap! <buffer> \1 𝟙
noremap! <buffer> \:= ≔
noremap! <buffer> \=: ≕
noremap! <buffer> \=? ≟
noremap! <buffer> \Box □
noremap! <buffer> \C ℂ
noremap! <buffer> \Downarrow ⇓
noremap! <buffer> \E 𝔼
noremap! <buffer> \F 𝔽
noremap! <buffer> \Join ⋈
noremap! <buffer> \Leftarrow ⇐
noremap! <buffer> \Leftrightarrow ⇔
noremap! <buffer> \N ℕ
noremap! <buffer> \Nearrow ⇗
noremap! <buffer> \Nwarrow ⇖
noremap! <buffer> \Q ℚ
noremap! <buffer> \R ℝ
noremap! <buffer> \Rightarrow ⇒
noremap! <buffer> \Searrow ⇘
noremap! <buffer> \Swarrow ⇙
noremap! <buffer> \Uparrow ⇑
noremap! <buffer> \Z ℤ
noremap! <buffer> \approx ≈
noremap! <buffer> \bot ⊥
noremap! <buffer> \boxdot ⊡
noremap! <buffer> \boxminus ⊟
noremap! <buffer> \boxplus ⊞
noremap! <buffer> \boxtimes ⊠
noremap! <buffer> \bullet •
noremap! <buffer> \cap ∩
noremap! <buffer> \cdot ⋅
noremap! <buffer> \cdots ⋯
noremap! <buffer> \checkmark ✓
noremap! <buffer> \circ ◦
noremap! <buffer> \cong ≅
noremap! <buffer> \contradiction ↯
noremap! <buffer> \cup ∪
noremap! <buffer> \dashv ⊣
noremap! <buffer> \diamond ◇
noremap! <buffer> \dots …
noremap! <buffer> \downarrow ↓
noremap! <buffer> \downharpoonleft ⇃
noremap! <buffer> \downharpoonright ⇂
noremap! <buffer> \ell ℓ
noremap! <buffer> \emptyset ∅
noremap! <buffer> \equiv ≡
noremap! <buffer> \exists ∃
noremap! <buffer> \flat ♭
noremap! <buffer> \forall ∀
noremap! <buffer> \geq ≥
noremap! <buffer> \iff ⇔
noremap! <buffer> \impliedby ⇐
noremap! <buffer> \implies ⇒
noremap! <buffer> \in ∈
noremap! <buffer> \infty ∞
noremap! <buffer> \int ∫
noremap! <buffer> \land ∧
noremap! <buffer> \langle ⟨
noremap! <buffer> \ldots …
noremap! <buffer> \leq ≤
noremap! <buffer> \leadsto ⇝
noremap! <buffer> \leftarrow ←
noremap! <buffer> \leftrightarrow ↔
noremap! <buffer> \longrightarrow ⟶ 
noremap! <buffer> \lor ∨
noremap! <buffer> \mapsto ↦
noremap! <buffer> \mid ∣
noremap! <buffer> \models ⊨
noremap! <buffer> \nearrow ↗
noremap! <buffer> \neg ¬
noremap! <buffer> \neq ≠
noremap! <buffer> \nequiv ≢
noremap! <buffer> \ni ∋
noremap! <buffer> \not\cong ≇
noremap! <buffer> \not\equiv ≢
noremap! <buffer> \not\exists ∄
noremap! <buffer> \not\in ∉
noremap! <buffer> \nwarrow ↖
noremap! <buffer> \odot ⊙
noremap! <buffer> \ominus ⊖
noremap! <buffer> \oplus ⊕
noremap! <buffer> \oslash ⊘
noremap! <buffer> \otimes ⊗
noremap! <buffer> \partial ∂
noremap! <buffer> \perp ⊥
noremap! <buffer> \pm ±
noremap! <buffer> \prec ≺
noremap! <buffer> \preccurlyeq ≼
noremap! <buffer> \prod ∏
noremap! <buffer> \qed ∎
noremap! <buffer> \rangle ⟩
noremap! <buffer> \searrow ↘
noremap! <buffer> \setminus ∖
noremap! <buffer> \sharp ♯
noremap! <buffer> \sim ∼
noremap! <buffer> \simeq ≃
noremap! <buffer> \sqcap ⊓
noremap! <buffer> \sqcup ⊔
noremap! <buffer> \sqrt √
noremap! <buffer> \sqsubset ⊏
noremap! <buffer> \sqsubseteq ⊑
noremap! <buffer> \sqsupset ⊐
noremap! <buffer> \sqsupseteq ⊒
noremap! <buffer> \star ✭
noremap! <buffer> \subset ⊂
noremap! <buffer> \subseteq ⊆
noremap! <buffer> \subsetneq ⊊
noremap! <buffer> \succ ≻
noremap! <buffer> \succcurlyeq ≽
noremap! <buffer> \sum ∑
noremap! <buffer> \supset ⊃
noremap! <buffer> \supseteq ⊇
noremap! <buffer> \supsetneq ⊋
noremap! <buffer> \swarrow ↙
noremap! <buffer> \textdegree °
noremap! <buffer> \textsection §
noremap! <buffer> \therefore ∴
noremap! <buffer> \times ×
noremap! <buffer> \to →
noremap! <buffer> \top ⊤
noremap! <buffer> \uparrow ↑
noremap! <buffer> \updownarrow ↕
noremap! <buffer> \updownarrows ⇅
noremap! <buffer> \upharpoonleft ↿
noremap! <buffer> \upharpoonright ↾
noremap! <buffer> \vdash ⊢
noremap! <buffer> \vdots ⋮

" Paired operators
noremap! <buffer> \ceil ⌈⌉<left>
noremap! <buffer> \floor ⌊⌋<left>
noremap! <buffer> \bracket ⟦⟧<left>
noremap! <buffer> \angle ⟨⟩<left>
noremap! <buffer> \aangle ⟪⟫<left>

" Greek alphabet...
noremap! <buffer> \alpha α
noremap! <buffer> \beta β
noremap! <buffer> \gamma γ
noremap! <buffer> \delta δ
noremap! <buffer> \epsilon ε
noremap! <buffer> \zeta ζ
noremap! <buffer> \eta η
noremap! <buffer> \theta θ
noremap! <buffer> \iota ι
noremap! <buffer> \kappa κ
noremap! <buffer> \lambda λ
noremap! <buffer> \mu μ
noremap! <buffer> \nu ν
noremap! <buffer> \xi ξ
noremap! <buffer> \omicron ο
noremap! <buffer> \pi π
noremap! <buffer> \rho ρ
noremap! <buffer> \stigma ς
noremap! <buffer> \sigma σ
noremap! <buffer> \tau τ
noremap! <buffer> \upsilon υ
noremap! <buffer> \phi ϕ
noremap! <buffer> \varphi φ
noremap! <buffer> \chi χ
noremap! <buffer> \psi ψ
noremap! <buffer> \omega ω

noremap! <buffer> \Alpha Α
noremap! <buffer> \Beta Β
noremap! <buffer> \Gamma Γ
noremap! <buffer> \Delta Δ
noremap! <buffer> \Epsilon Ε
noremap! <buffer> \Zeta Ζ
noremap! <buffer> \Eta Η
noremap! <buffer> \Theta Θ
noremap! <buffer> \Iota Ι
noremap! <buffer> \Kappa Κ
noremap! <buffer> \Lambda Λ
noremap! <buffer> \Mu Μ
noremap! <buffer> \Nu Ν
noremap! <buffer> \Xi Ξ
noremap! <buffer> \Omicron Ο
noremap! <buffer> \Pi Π
noremap! <buffer> \Rho Ρ
noremap! <buffer> \Sigma Σ
noremap! <buffer> \Tau Τ
noremap! <buffer> \Upsilon Υ
noremap! <buffer> \Phi Φ
noremap! <buffer> \Chi Χ
noremap! <buffer> \Psi Ψ
noremap! <buffer> \Omega Ω

