" agda_unicode.vim - LaTeX-style bindings for Unicode input

" Superscripts
inoremap <buffer> ^0 ⁰
inoremap <buffer> ^1 ¹
inoremap <buffer> ^2 ²
inoremap <buffer> ^3 ³
inoremap <buffer> ^4 ⁴
inoremap <buffer> ^5 ⁵
inoremap <buffer> ^6 ⁶
inoremap <buffer> ^7 ⁷
inoremap <buffer> ^8 ⁸
inoremap <buffer> ^9 ⁹
inoremap <buffer> ^+ ⁺
inoremap <buffer> ^- ⁻
inoremap <buffer> ^= ⁼
inoremap <buffer> ^( ⁽
inoremap <buffer> ^) ⁾
inoremap <buffer> ^n ⁿ
inoremap <buffer> ^i ⁱ

" Subscripts
inoremap <buffer> \_0 ₀
inoremap <buffer> \_1 ₁
inoremap <buffer> \_2 ₂
inoremap <buffer> \_3 ₃
inoremap <buffer> \_4 ₄
inoremap <buffer> \_5 ₅
inoremap <buffer> \_6 ₆
inoremap <buffer> \_7 ₇
inoremap <buffer> \_8 ₈
inoremap <buffer> \_9 ₉
inoremap <buffer> \_+ ₊
inoremap <buffer> \_- ₋
inoremap <buffer> \_= ₌
inoremap <buffer> \_( ₍
inoremap <buffer> \_i ᵢ
inoremap <buffer> \_j ⱼ
inoremap <buffer> \_) ₎

" Arrows (but don't delay inserting comments)
inoremap <buffer> -> →
inoremap <buffer> -- --
inoremap <buffer> <-- ←
inoremap <buffer> <--> ↔
inoremap <buffer> ==> ⇒
inoremap <buffer> <== ⇐
inoremap <buffer> <==> ⇔

" Symbols from mathematics and logic, LaTeX style
inoremap <buffer> \1 𝟙
inoremap <buffer> \:= ≔
inoremap <buffer> \=: ≕
inoremap <buffer> \=? ≟
inoremap <buffer> \Box □
inoremap <buffer> \C ℂ
inoremap <buffer> \Downarrow ⇓
inoremap <buffer> \E 𝔼
inoremap <buffer> \F 𝔽
inoremap <buffer> \Join ⋈
inoremap <buffer> \Leftarrow ⇐
inoremap <buffer> \Leftrightarrow ⇔
inoremap <buffer> \N ℕ
inoremap <buffer> \Nearrow ⇗
inoremap <buffer> \Nwarrow ⇖
inoremap <buffer> \Q ℚ
inoremap <buffer> \R ℝ
inoremap <buffer> \Rightarrow ⇒
inoremap <buffer> \Searrow ⇘
inoremap <buffer> \Swarrow ⇙
inoremap <buffer> \Uparrow ⇑
inoremap <buffer> \Z ℤ
inoremap <buffer> \approx ≈
inoremap <buffer> \bot ⊥
inoremap <buffer> \boxdot ⊡
inoremap <buffer> \boxminus ⊟
inoremap <buffer> \boxplus ⊞
inoremap <buffer> \boxtimes ⊠
inoremap <buffer> \bullet •
inoremap <buffer> \cap ∩
inoremap <buffer> \cdot ⋅
inoremap <buffer> \cdots ⋯
inoremap <buffer> \checkmark ✓
inoremap <buffer> \circ ◦
inoremap <buffer> \cong ≅
inoremap <buffer> \contradiction ↯
inoremap <buffer> \cup ∪
inoremap <buffer> \dashv ⊣
inoremap <buffer> \diamond ◇
inoremap <buffer> \dots …
inoremap <buffer> \downarrow ↓
inoremap <buffer> \downharpoonleft ⇃
inoremap <buffer> \downharpoonright ⇂
inoremap <buffer> \ell ℓ
inoremap <buffer> \emptyset ∅
inoremap <buffer> \equiv ≡
inoremap <buffer> \exists ∃
inoremap <buffer> \flat ♭
inoremap <buffer> \forall ∀
inoremap <buffer> \geq ≥
inoremap <buffer> \iff ⇔
inoremap <buffer> \impliedby ⇐
inoremap <buffer> \implies ⇒
inoremap <buffer> \in ∈
inoremap <buffer> \infty ∞
inoremap <buffer> \int ∫
inoremap <buffer> \land ∧
inoremap <buffer> \langle ⟨
inoremap <buffer> \ldots …
inoremap <buffer> \leq ≤
inoremap <buffer> \leadsto ⇝
inoremap <buffer> \leftarrow ←
inoremap <buffer> \leftrightarrow ↔
inoremap <buffer> \longrightarrow ⟶ 
inoremap <buffer> \lor ∨
inoremap <buffer> \mapsto ↦
inoremap <buffer> \mid ∣
inoremap <buffer> \models ⊨
inoremap <buffer> \nearrow ↗
inoremap <buffer> \neg ¬
inoremap <buffer> \neq ≠
inoremap <buffer> \nequiv ≢
inoremap <buffer> \ni ∋
inoremap <buffer> \not\cong ≇
inoremap <buffer> \not\equiv ≢
inoremap <buffer> \not\exists ∄
inoremap <buffer> \not\in ∉
inoremap <buffer> \nwarrow ↖
inoremap <buffer> \odot ⊙
inoremap <buffer> \ominus ⊖
inoremap <buffer> \oplus ⊕
inoremap <buffer> \oslash ⊘
inoremap <buffer> \otimes ⊗
inoremap <buffer> \partial ∂
inoremap <buffer> \perp ⊥
inoremap <buffer> \pm ±
inoremap <buffer> \prec ≺
inoremap <buffer> \preccurlyeq ≼
inoremap <buffer> \prod ∏
inoremap <buffer> \qed ∎
inoremap <buffer> \rangle ⟩
inoremap <buffer> \searrow ↘
inoremap <buffer> \setminus ∖
inoremap <buffer> \sharp ♯
inoremap <buffer> \sim ∼
inoremap <buffer> \simeq ≃
inoremap <buffer> \sqcap ⊓
inoremap <buffer> \sqcup ⊔
inoremap <buffer> \sqrt √
inoremap <buffer> \sqsubset ⊏
inoremap <buffer> \sqsubseteq ⊑
inoremap <buffer> \sqsupset ⊐
inoremap <buffer> \sqsupseteq ⊒
inoremap <buffer> \star ✭
inoremap <buffer> \subset ⊂
inoremap <buffer> \subseteq ⊆
inoremap <buffer> \subsetneq ⊊
inoremap <buffer> \succ ≻
inoremap <buffer> \succcurlyeq ≽
inoremap <buffer> \sum ∑
inoremap <buffer> \supset ⊃
inoremap <buffer> \supseteq ⊇
inoremap <buffer> \supsetneq ⊋
inoremap <buffer> \swarrow ↙
inoremap <buffer> \textdegree °
inoremap <buffer> \textsection §
inoremap <buffer> \therefore ∴
inoremap <buffer> \times ×
inoremap <buffer> \to →
inoremap <buffer> \top ⊤
inoremap <buffer> \uparrow ↑
inoremap <buffer> \updownarrow ↕
inoremap <buffer> \updownarrows ⇅
inoremap <buffer> \upharpoonleft ↿
inoremap <buffer> \upharpoonright ↾
inoremap <buffer> \vdash ⊢
inoremap <buffer> \vdots ⋮

" Paired operators
inoremap <buffer> \ceil ⌈⌉<left>
inoremap <buffer> \floor ⌊⌋<left>
inoremap <buffer> \bracket ⟦⟧<left>
inoremap <buffer> \angle ⟨⟩<left>
inoremap <buffer> \aangle ⟪⟫<left>

" Greek alphabet...
inoremap <buffer> \alpha α
inoremap <buffer> \beta β
inoremap <buffer> \gamma γ
inoremap <buffer> \delta δ
inoremap <buffer> \epsilon ε
inoremap <buffer> \zeta ζ
inoremap <buffer> \eta η
inoremap <buffer> \theta θ
inoremap <buffer> \iota ι
inoremap <buffer> \kappa κ
inoremap <buffer> \lambda λ
inoremap <buffer> \mu μ
inoremap <buffer> \nu ν
inoremap <buffer> \xi ξ
inoremap <buffer> \omicron ο
inoremap <buffer> \pi π
inoremap <buffer> \rho ρ
inoremap <buffer> \stigma ς
inoremap <buffer> \sigma σ
inoremap <buffer> \tau τ
inoremap <buffer> \upsilon υ
inoremap <buffer> \phi ϕ
inoremap <buffer> \varphi φ
inoremap <buffer> \chi χ
inoremap <buffer> \psi ψ
inoremap <buffer> \omega ω

inoremap <buffer> \Alpha Α
inoremap <buffer> \Beta Β
inoremap <buffer> \Gamma Γ
inoremap <buffer> \Delta Δ
inoremap <buffer> \Epsilon Ε
inoremap <buffer> \Zeta Ζ
inoremap <buffer> \Eta Η
inoremap <buffer> \Theta Θ
inoremap <buffer> \Iota Ι
inoremap <buffer> \Kappa Κ
inoremap <buffer> \Lambda Λ
inoremap <buffer> \Mu Μ
inoremap <buffer> \Nu Ν
inoremap <buffer> \Xi Ξ
inoremap <buffer> \Omicron Ο
inoremap <buffer> \Pi Π
inoremap <buffer> \Rho Ρ
inoremap <buffer> \Sigma Σ
inoremap <buffer> \Tau Τ
inoremap <buffer> \Upsilon Υ
inoremap <buffer> \Phi Φ
inoremap <buffer> \Chi Χ
inoremap <buffer> \Psi Ψ
inoremap <buffer> \Omega Ω

